### ISSUE TITLE
Troubles installing

### ISSUE THREAD

**Issue by dzwiener** [SmokinCaterpillar/TrufflePig#25]
I am trying to run main.py, but when I do I get the error:
ImportError: No module named trufflepig.bchain.getdata
I feel like I missed a step, but I added the PYTHONPATH to my bash profile like specified.

**Comment by SmokinCaterpillar** [comment]
Hi, sorry for my late answer. Did you add the project path or the package path instead?

**Comment by dzwiener** [comment]
I add the project path.

**Comment by SmokinCaterpillar** [comment]
Are you using Linux? Have you tried other ways adding the directory to your PYTHONPATH (e.g. using PyCharm)?

Or have you tried:
``$ export PYTHONPATH=$PYTHONPATH:<path_to_project>``?
